#|__________________________________________________________________________________________|
#| C                         F                  K                                       :)  |
#|    O                           O                  N                               !      |
#|        N                             R                 O                       K         |
#|            F                                               C                C            |
#|                I                                               K        A                |
#|                    G                                                B                    |
#|__________________________________________________________________________________________|

# ______________________________________________________________________________________________________________________
# ______________________________________________________________________________________________________________________
#                                                -=  I  N  F  O  =-


#This is the configuration for this plugin. Contact me on discord/email to report bugs/suggestions:

# Discord: Bo0ked61#8643    ||    Email: booked1234512@gmail.com    ||    Discord would be easier to reach me.

# Subscribe to booked61 on youtube and rate this plugin! Youtube - https://bit.ly/3dFPoDK

# I'm always open to recommendations on plugins for you! Please recommend things that I can make! :)

# ______________________________________________________________________________________________________________________
# ______________________________________________________________________________________________________________________
#                                           -=  M  E  S  S  A  G  E  S  =-


# Coming out soon!

# ______________________________________________________________________________________________________________________
# ______________________________________________________________________________________________________________________
#                                            -=  P  L  A  Y  E  R  S  =-


# Set the amount of knockback for players:
knockback-of-players: 5


# Should there be a delay on the knockback for players? (In seconds)
# Set to zero if you don't want a delay.
delay-of-kb-players: 1


# ______________________________________________________________________________________________________________________
# ______________________________________________________________________________________________________________________
#                                                  -=  M  O  B  S  =-

# Sets the amount of knockback for mobs:
knockback-of-mobs: 5




# Should there be a delay on the knockback for mobs? (In seconds)
# Set to zero if you don't want a delay.
delay-of-kb-mobs: 1

# ______________________________________________________________________________________________________________________
# ______________________________________________________________________________________________________________________


# End of config